name: Update Daily EPG

on:
  schedule:
    - cron: '0 5 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Forza i permessi di scrittura

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests

      - name: Run merge script
        run: python merge_epg.py

      - name: Commit and push changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add join.epg
          
          # Controlla se ci sono differenze. Se sì, fa il commit e push.
          if git diff --staged --quiet; then
            echo "Nessuna modifica rilevata nel file join.epg"
          else
            git commit -m "Update EPG $(date +'%Y-%m-%d %H:%M')"
            git push origin main
          fi
